---
- name: Configure chrony
  ansible.builtin.copy:
    dest: /etc/chrony/chrony.conf
    mode: '0644'
    content: |
      pool {{ mylab_ntp_servers[0] }} iburst
      pool {{ mylab_ntp_servers[1] }} iburst
      driftfile /var/lib/chrony/chrony.drift
      makestep 1.0 3
      rtcsync
      logdir /var/log/chrony
  notify: Restart chrony

- name: Ensure chrony is enabled
  ansible.builtin.service:
    name: chrony
    enabled: true
    state: started
