---
mylab_site: dc1

hypervisor_bridges:
  - name: br-mgmt-dc1
    address: 10.10.10.11/24
    gateway4: 10.10.10.1
    dns_servers: "{{ mylab_dns_servers }}"
    physical_nic: eno1

  - name: br-underlay-dc1
    physical_nic: eno2

  - name: br-prod1
    physical_nic: null

hypervisor_vms:
  - name: bastion1.dc1.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 40
    role: bastion
    rp_filter_mode: 1
    allow_tcp_forwarding: "yes"
    nft_extra_tcp_in:
      - 443
    nics:
      - bridge: br-mgmt-dc1
        mac: "52:54:00:10:10:10"
        address: 10.10.10.10/24
        gateway4: 10.10.10.1
        nameservers: "{{ mylab_dns_servers }}"

  - name: r1-dc1.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: router
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc1
        mac: "52:54:00:10:50:01"
        address: 10.10.50.1/24

  - name: r2-dc1.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: router
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc1
        mac: "52:54:00:10:50:02"
        address: 10.10.50.2/24

  - name: leaf1-dc1.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: leaf
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc1
        mac: "52:54:00:10:50:11"
        address: 10.10.50.11/24

  - name: leaf2-dc1.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: leaf
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc1
        mac: "52:54:00:10:50:12"
        address: 10.10.50.12/24

  - name: prod1-cp1.dc1.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-control-plane
    rp_filter_mode: 2
    nics:
      - bridge: br-prod1
        mac: "52:54:00:10:20:11"
        address: 10.10.20.11/24
        gateway4: 10.10.20.1
        nameservers: "{{ mylab_dns_servers }}"

  - name: prod1-w1.dc1.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-worker
    rp_filter_mode: 2
    nics:
      - bridge: br-prod1
        mac: "52:54:00:10:20:21"
        address: 10.10.20.21/24
        gateway4: 10.10.20.1
        nameservers: "{{ mylab_dns_servers }}"

  - name: prod1-w2.dc1.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-worker
    rp_filter_mode: 2
    nics:
      - bridge: br-prod1
        mac: "52:54:00:10:20:22"
        address: 10.10.20.22/24
        gateway4: 10.10.20.1
        nameservers: "{{ mylab_dns_servers }}"
