---
mylab_site: dc2

hypervisor_bridges:
  - name: br-mgmt-dc2
    address: 10.20.10.11/24
    gateway4: 10.20.10.1
    dns_servers: "{{ mylab_dns_servers }}"
    physical_nic: eno1

  - name: br-underlay-dc2
    physical_nic: eno2

  - name: br-prod2
    physical_nic: null

hypervisor_vms:
  - name: r1-dc2.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: router
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc2
        mac: "52:54:00:20:50:01"
        address: 10.20.50.1/24

  - name: r2-dc2.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: router
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc2
        mac: "52:54:00:20:50:02"
        address: 10.20.50.2/24

  - name: leaf1-dc2.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: leaf
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc2
        mac: "52:54:00:20:50:11"
        address: 10.20.50.11/24

  - name: leaf2-dc2.lab
    vcpus: 2
    memory_mb: 4096
    disk_gb: 20
    role: leaf
    rp_filter_mode: 0
    nft_enabled: false
    nics:
      - bridge: br-underlay-dc2
        mac: "52:54:00:20:50:12"
        address: 10.20.50.12/24

  - name: prod2-cp1.dc2.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-control-plane
    rp_filter_mode: 2
    nics:
      - bridge: br-prod2
        mac: "52:54:00:20:20:11"
        address: 10.20.20.11/24
        gateway4: 10.20.20.1
        nameservers: "{{ mylab_dns_servers }}"

  - name: prod2-w1.dc2.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-worker
    rp_filter_mode: 2
    nics:
      - bridge: br-prod2
        mac: "52:54:00:20:20:21"
        address: 10.20.20.21/24
        gateway4: 10.20.20.1
        nameservers: "{{ mylab_dns_servers }}"

  - name: prod2-w2.dc2.lab
    vcpus: 4
    memory_mb: 8192
    disk_gb: 80
    role: k8s-worker
    rp_filter_mode: 2
    nics:
      - bridge: br-prod2
        mac: "52:54:00:20:20:22"
        address: 10.20.20.22/24
        gateway4: 10.20.20.1
        nameservers: "{{ mylab_dns_servers }}"
