host_role: router
primary_interface: eth0
mgmt_ip: 10.10.10.11/24
mgmt_gw: 10.10.10.1
loopback_ip: 10.255.1.1/32
frr_router_id: 10.255.1.1
transit_interfaces:
  - name: eth1
    ip: 10.10.99.1/30
  - name: eth2
    ip: 10.10.99.5/30