---
- name: Install unattended-upgrades packages
  ansible.builtin.apt:
    name: "{{ unattended_upgrades_packages }}"
    state: present
  when: mylab_unattended_upgrades | bool

- name: Enable periodic apt updates
  ansible.builtin.copy:
    dest: "{{ unattended_auto_upgrades_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
  when: mylab_unattended_upgrades | bool

- name: Configure unattended upgrades
  ansible.builtin.copy:
    dest: "{{ unattended_config_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      Unattended-Upgrade::Origins-Pattern {
              "origin=Debian,codename=${distro_codename},label=Debian-Security";
      };

      Unattended-Upgrade::Package-Blacklist {
      };

      Unattended-Upgrade::Automatic-Reboot "{{ 'true' if mylab_reboot_if_required else 'false' }}";
      Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_reboot_time }}";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::SyslogEnable "true";
  when: mylab_unattended_upgrades | bool

- name: Ensure unattended-upgrades service is enabled and started
  ansible.builtin.service:
    name: "{{ unattended_service_name }}"
    enabled: true
    state: started
  when: mylab_unattended_upgrades | bool