- name: Configure nftables
  copy:
    dest: /etc/nftables.conf
    mode: '0644'
    content: |
      flush ruleset

      table inet filter {
        chain input {
          type filter hook input priority 0;
          policy drop;

          iif lo accept
          ct state established,related accept

          ip protocol icmp accept
          ip6 nexthdr ipv6-icmp accept

          tcp dport 22 ip saddr 10.10.10.10 accept

          udp dport { 123, 53 } accept
          tcp dport 53 accept

          tcp dport { 179 } accept
          ospf accept
          vrrp accept

          tcp dport { 6443, 2379, 2380, 10250, 10257, 10259 } accept
          udp dport { 8472, 4789 } accept
          tcp dport { 30000-32767 } accept
        }

        chain forward {
          type filter hook forward priority 0;
          policy accept;
        }

        chain output {
          type filter hook output priority 0;
          policy accept;
        }
      }

- name: Enable nftables
  service:
    name: nftables
    state: restarted
    enabled: true