---
ansible_user: debian
ansible_become: true
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: "~/.ssh/jmachine"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

mylab_domain: lab
mylab_timezone: Europe/Amsterdam

mylab_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

mylab_ntp_servers:
  - pool.ntp.org

mylab_admin_user: automation
mylab_admin_groups:
  - sudo

mylab_disable_root_ssh: true
mylab_password_authentication: false
mylab_manage_ufw: false

mylab_kubernetes_version: v1.31.0
mylab_pod_cidr: 10.244.0.0/16
mylab_service_cidr: 10.96.0.0/12
mylab_container_runtime: containerd

mylab_sysctl_common:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.conf.all.rp_filter: 0
  net.ipv4.conf.default.rp_filter: 0

mylab_common_packages:
  - qemu-guest-agent
  - curl
  - wget
  - vim
  - git
  - rsync
  - sudo
  - bash-completion
  - ca-certificates
  - gnupg
  - lsb-release
  - net-tools
  - tcpdump
  - jq
  - unzip

mylab_router_packages:
  - frr

mylab_bastion_packages:
  - tmux
  - htop

mylab_k8s_packages:
  - apt-transport-https

mylab_frr_defaults:
  bgp_as_dc1: 65001
  bgp_as_dc2: 65002

mylab_ssh_hardening:
  permit_root_login: "no"
  password_authentication: "no"
  pubkey_authentication: "yes"
  challenge_response_authentication: "no"
  use_pam: "yes"
  x11_forwarding: "no"
  allow_tcp_forwarding: "yes"
  client_alive_interval: 300
  client_alive_count_max: 2

# ---- required by keepalived_vrrp ----
mylab_vrrp_auth_pass: "mylabvrrp42"
mylab_vrrp_mgmt_vip: 192.168.50.254
mylab_vrrp_dc1_infra_vip: 10.10.50.254
mylab_vrrp_dc2_infra_vip: 10.20.50.254

# ---- required by router_frr ----
mylab_inter_dc_enable_bgp: false
mylab_bgp_asn_dc1: 65001
mylab_bgp_asn_dc2: 65002
mylab_bgp_rr_loopback_dc1: 10.255.0.1
mylab_bgp_rr_loopback_dc2: 10.255.0.21

# ---- required by router_nat ----
mylab_nat_allowed_sources:
  - 192.168.50.0/24
  - 10.10.20.0/24
  - 10.20.20.0/24
  - 10.10.50.0/24
  - 10.20.50.0/24