---
mylab_upstream_mode: routed
mylab_uplink_interface: tun0
mylab_wan_interface: tun0
mylab_timezone: Europe/Amsterdam

# Host-side bridge IPs
mylab_mgmt_bridge_cidr: 192.168.50.253/24
mylab_wan_bridge_cidr: 172.16.255.1/24
mylab_dc1_bridge_cidr: 10.10.50.253/24
mylab_dc2_bridge_cidr: 10.20.50.253/24

mylab_nat_source_subnets:
  - 172.16.255.0/24
  - 192.168.50.0/24
  - 10.10.20.0/24
  - 10.20.20.0/24
  - 10.10.50.0/24
  - 10.20.50.0/24

mylab_internal_bridge_ifaces:
  - br-mgmt
  - br-wan
  - br-dc1
  - br-dc2

mylab_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

mylab_root_dir: /var/lib/mylab
mylab_images_dir: "{{ mylab_root_dir }}/images"
mylab_disks_dir: "{{ mylab_root_dir }}/disks"
mylab_seed_dir: "{{ mylab_root_dir }}/seed"
mylab_runtime_dir: "{{ mylab_root_dir }}/runtime"
mylab_logs_dir: "{{ mylab_root_dir }}/logs"
mylab_scripts_dir: /usr/local/libexec/mylab
mylab_systemd_dir: /etc/systemd/system

mylab_cloud_image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
mylab_cloud_image_name: debian-12-genericcloud-amd64.qcow2

mylab_default_vcpu: 2
mylab_default_memory_mb: 2048
mylab_default_disk_gb: 20
mylab_default_username: debian

# Use your real keypair here
mylab_ssh_public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/jmachine.pub"
mylab_guest_ansible_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/jmachine"
mylab_ssh_public_key: "{{ lookup('file', mylab_ssh_public_key_file) | trim }}"

mylab_ipam_vm_file: "{{ playbook_dir }}/../../ipam/generated/hypervisor-vms.yaml"

mylab_guest_ansible_user: debian
mylab_guest_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

mylab_allowed_bridges:
  - br-mgmt
  - br-wan
  - br-dc1
  - br-dc2

mylab_remove_packages:
  - telnet
  - rsh-client
  - rsh-redone-client
  - nis

mylab_default_packages_extra: []

mylab_qemu_bridge_helper_path: /usr/lib/qemu/qemu-bridge-helper