---
mylab_upstream_mode: routed
mylab_uplink_interface: wlp0s20f3

# Host-side bridge IPs. Keep them unique and never reuse them on guests.
mylab_mgmt_bridge_cidr: 192.168.50.253/24
mylab_wan_bridge_cidr: 172.16.255.1/24
mylab_dc1_bridge_cidr: 10.10.50.253/24
mylab_dc2_bridge_cidr: 10.20.50.253/24

mylab_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

mylab_root_dir: /var/lib/mylab
mylab_images_dir: "{{ mylab_root_dir }}/images"
mylab_disks_dir: "{{ mylab_root_dir }}/disks"
mylab_seed_dir: "{{ mylab_root_dir }}/seed"
mylab_runtime_dir: "{{ mylab_root_dir }}/runtime"
mylab_logs_dir: "{{ mylab_root_dir }}/logs"
mylab_scripts_dir: /usr/local/libexec/mylab
mylab_systemd_dir: /etc/systemd/system

mylab_cloud_image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
mylab_cloud_image_name: debian-12-genericcloud-amd64.qcow2

mylab_default_vcpu: 2
mylab_default_memory_mb: 2048
mylab_default_disk_gb: 20
mylab_default_username: debian

mylab_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIHe3ys785Q0MwXnuHzZA8oHHTr/4+VqvowuoZErIcEz omid@thismachine"

mylab_ipam_vm_file: "{{ playbook_dir }}/../../ipam/generated/hypervisor-vms.yaml"

# Guest SSH settings for the hardening/bootstrap play
mylab_guest_ansible_user: debian
mylab_guest_ansible_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/jmachine"
mylab_guest_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

# Bridges QEMU is allowed to attach to
mylab_allowed_bridges:
  - br-mgmt
  - br-wan
  - br-dc1
  - br-dc2

mylab_remove_packages:
  - telnet
  - rsh-client
  - rsh-redone-client
  - nis

mylab_default_packages_extra: []

mylab_qemu_bridge_helper_path: /usr/lib/qemu/qemu-bridge-helper