---
all:
  children:
    hypervisors:
      hosts:
        mylab-host:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: omid

    guests:
      hosts:
        bastion1.dc1.lab:
          ansible_host: 10.10.10.10

        r1-dc1.lab:
          ansible_host: 10.10.50.1
        r2-dc1.lab:
          ansible_host: 10.10.50.2
        leaf1-dc1.lab:
          ansible_host: 10.10.50.11
        leaf2-dc1.lab:
          ansible_host: 10.10.50.12

        prod1-cp1.dc1.lab:
          ansible_host: 10.10.20.11
        prod1-cp2.dc1.lab:
          ansible_host: 10.10.20.12
        prod1-w1.dc1.lab:
          ansible_host: 10.10.20.21
        prod1-w2.dc1.lab:
          ansible_host: 10.10.20.22

        r1-dc2.lab:
          ansible_host: 10.20.50.1
        r2-dc2.lab:
          ansible_host: 10.20.50.2
        leaf1-dc2.lab:
          ansible_host: 10.20.50.11
        leaf2-dc2.lab:
          ansible_host: 10.20.50.12

        prod2-cp1.dc2.lab:
          ansible_host: 10.20.20.11
        prod2-cp2.dc2.lab:
          ansible_host: 10.20.20.12
        prod2-w1.dc2.lab:
          ansible_host: 10.20.20.21
        prod2-w2.dc2.lab:
          ansible_host: 10.20.20.22
