---
all:
  vars:
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3

  children:
    hypervisors:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3

    guests:
      hosts:
        bastion1.dc1.lab:
          ansible_host: 10.10.10.10

        r1-dc1.lab:
          ansible_host: 10.10.50.1
        r2-dc1.lab:
          ansible_host: 10.10.50.2
        leaf1-dc1.lab:
          ansible_host: 10.10.50.11
        leaf2-dc1.lab:
          ansible_host: 10.10.50.12

        r1-dc2.lab:
          ansible_host: 10.20.50.1
        r2-dc2.lab:
          ansible_host: 10.20.50.2
        leaf1-dc2.lab:
          ansible_host: 10.20.50.11
        leaf2-dc2.lab:
          ansible_host: 10.20.50.12

        prod1-cp1.dc1.lab:
          ansible_host: 10.10.20.11
        prod1-w1.dc1.lab:
          ansible_host: 10.10.20.21
        prod1-w2.dc1.lab:
          ansible_host: 10.10.20.22

        prod2-cp1.dc2.lab:
          ansible_host: 10.20.20.11
        prod2-w1.dc2.lab:
          ansible_host: 10.20.20.21
        prod2-w2.dc2.lab:
          ansible_host: 10.20.20.22

    bastion:
      hosts:
        bastion1.dc1.lab:

    routers:
      hosts:
        r1-dc1.lab:
        r2-dc1.lab:
        r1-dc2.lab:
        r2-dc2.lab:

    leafs:
      hosts:
        leaf1-dc1.lab:
        leaf2-dc1.lab:
        leaf1-dc2.lab:
        leaf2-dc2.lab:

    kubernetes_control_plane:
      hosts:
        prod1-cp1.dc1.lab:
        prod2-cp1.dc2.lab:

    kubernetes_workers:
      hosts:
        prod1-w1.dc1.lab:
        prod1-w2.dc1.lab:
        prod2-w1.dc2.lab:
        prod2-w2.dc2.lab:
