---
all:
  children:
    bastion:
      hosts:
        bastion1.dc1.lab:
          ansible_host: 192.168.50.10

    routers:
      hosts:
        r1-dc1.lab:
          ansible_host: 192.168.50.1
        r2-dc1.lab:
          ansible_host: 192.168.50.2
        r1-dc2.lab:
          ansible_host: 192.168.50.41
        r2-dc2.lab:
          ansible_host: 192.168.50.42

    leafs:
      hosts:
        leaf1-dc1.lab:
          ansible_host: 192.168.50.11
        leaf2-dc1.lab:
          ansible_host: 192.168.50.12
        leaf1-dc2.lab:
          ansible_host: 192.168.50.51
        leaf2-dc2.lab:
          ansible_host: 192.168.50.52

    kubernetes_control_plane:
      hosts:
        prod1-cp1.dc1.lab:
          ansible_host: 192.168.50.21
        prod2-cp1.dc2.lab:
          ansible_host: 192.168.50.61

    kubernetes_workers:
      hosts:
        prod1-w1.dc1.lab:
          ansible_host: 192.168.50.31
        prod1-w2.dc1.lab:
          ansible_host: 192.168.50.32
        prod2-w1.dc2.lab:
          ansible_host: 192.168.50.71
        prod2-w2.dc2.lab:
          ansible_host: 192.168.50.72

    network_devices:
      children:
        routers:
        leafs:

    kubernetes:
      children:
        kubernetes_control_plane:
        kubernetes_workers:

    linux:
      children:
        bastion:
        network_devices:
        kubernetes: