---
all:
  vars:
    ansible_user: automation
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:
    linux:
      hosts:
        bastion1.dc1.lab:
        r1-dc1.lab:
        r2-dc1.lab:
        leaf1-dc1.lab:
        leaf2-dc1.lab:
        r1-dc2.lab:
        r2-dc2.lab:
        leaf1-dc2.lab:
        leaf2-dc2.lab:
        prod1-cp1.dc1.lab:
        prod1-w1.dc1.lab:
        prod1-w2.dc1.lab:
        prod2-cp1.dc2.lab:
        prod2-w1.dc2.lab:
        prod2-w2.dc2.lab:

    bastion:
      hosts:
        bastion1.dc1.lab:

    routers:
      hosts:
        r1-dc1.lab:
          router_dc: dc1
          router_id: 10.255.0.1
          mgmt_ip: 192.168.50.11
          infra_ip: 10.10.50.1
          wan_ip: 172.16.255.11
          vrrp_priority_mgmt: 200
          vrrp_priority_infra: 200
          nat_inside_interfaces: ["eth0", "eth1"]
          nat_outside_interface: eth2
        r2-dc1.lab:
          router_dc: dc1
          router_id: 10.255.0.2
          mgmt_ip: 192.168.50.12
          infra_ip: 10.10.50.2
          wan_ip: 172.16.255.12
          vrrp_priority_mgmt: 100
          vrrp_priority_infra: 100
          nat_inside_interfaces: ["eth0", "eth1"]
          nat_outside_interface: eth2
        r1-dc2.lab:
          router_dc: dc2
          router_id: 10.255.0.21
          mgmt_ip: 192.168.50.51
          infra_ip: 10.20.50.1
          wan_ip: 172.16.255.21
          vrrp_priority_mgmt: 200
          vrrp_priority_infra: 200
          nat_inside_interfaces: ["eth0", "eth1"]
          nat_outside_interface: eth2
        r2-dc2.lab:
          router_dc: dc2
          router_id: 10.255.0.22
          mgmt_ip: 192.168.50.52
          infra_ip: 10.20.50.2
          wan_ip: 172.16.255.22
          vrrp_priority_mgmt: 100
          vrrp_priority_infra: 100
          nat_inside_interfaces: ["eth0", "eth1"]
          nat_outside_interface: eth2

    leafs:
      hosts:
        leaf1-dc1.lab:
          leaf_dc: dc1
          leaf_router_vip: 10.10.50.254
        leaf2-dc1.lab:
          leaf_dc: dc1
          leaf_router_vip: 10.10.50.254
        leaf1-dc2.lab:
          leaf_dc: dc2
          leaf_router_vip: 10.20.50.254
        leaf2-dc2.lab:
          leaf_dc: dc2
          leaf_router_vip: 10.20.50.254

    kubernetes:
      children:
        kube_control_plane:
          hosts:
            prod1-cp1.dc1.lab:
            prod2-cp1.dc2.lab:
        kube_workers:
          hosts:
            prod1-w1.dc1.lab:
            prod1-w2.dc1.lab:
            prod2-w1.dc2.lab:
            prod2-w2.dc2.lab:

    dc1:
      hosts:
        bastion1.dc1.lab:
        r1-dc1.lab:
        r2-dc1.lab:
        leaf1-dc1.lab:
        leaf2-dc1.lab:
        prod1-cp1.dc1.lab:
        prod1-w1.dc1.lab:
        prod1-w2.dc1.lab:

    dc2:
      hosts:
        r1-dc2.lab:
        r2-dc2.lab:
        leaf1-dc2.lab:
        leaf2-dc2.lab:
        prod2-cp1.dc2.lab:
        prod2-w1.dc2.lab:
        prod2-w2.dc2.lab: