---
- name: Install FRR
  ansible.builtin.apt:
    name:
      - frr
      - frr-pythontools
    state: present

- name: Configure router interfaces
  ansible.builtin.template:
    src: interfaces-router.j2
    dest: /etc/network/interfaces.d/mylab-router.cfg
    mode: '0644'
  notify: Restart networking

- name: Configure FRR daemons
  ansible.builtin.copy:
    dest: /etc/frr/daemons
    mode: '0644'
    content: |
      zebra={{ router_frr_manage_daemons.zebra }}
      bgpd={{ router_frr_manage_daemons.bgpd }}
      ospfd={{ router_frr_manage_daemons.ospfd }}
      staticd={{ router_frr_manage_daemons.staticd }}
  notify: Restart frr

- name: Configure FRR router config
  ansible.builtin.template:
    src: frr-router.conf.j2
    dest: /etc/frr/frr.conf
    mode: '0640'
    owner: frr
    group: frr
  notify: Restart frr

- name: Ensure services enabled
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - networking
    - frr
