---
- name: Install FRR
  ansible.builtin.apt:
    name:
      - frr
      - frr-pythontools
    state: present
    update_cache: true

- name: Enable FRR daemons
  ansible.builtin.copy:
    dest: /etc/frr/daemons
    owner: frr
    group: frr
    mode: "0640"
    content: |
      zebra=yes
      bgpd={{ 'yes' if mylab_inter_dc_enable_bgp else 'no' }}
      ospfd=yes
      ospf6d=no
      ripd=no
      ripngd=no
      isisd=no
      pimd=no
      ldpd=no
      nhrpd=no
      eigrpd=no
      babeld=no
      sharpd=no
      pbrd=no
      bfdd=no
      fabricd=no
      vrrpd=no
  notify: restart frr

- name: Render FRR config
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: "0640"
  notify: restart frr

- name: Enable FRR
  ansible.builtin.service:
    name: frr
    state: started
    enabled: true