---
node_role: bastion
dc: dc1
mylab_primary_ip: 10.10.10.10
mylab_primary_interface: ens18
network_interfaces:
  - name: ens18
    address: 10.10.10.10/24
    gateway: 10.10.10.1
    dns: "{{ mylab_dns_servers }}"
