---
node_role: leaf
dc: dc1

leaf_asn: 65100
router_id: 10.255.0.11
loopback_ip: 10.255.0.11/32

mylab_primary_ip: 10.10.50.11
mylab_primary_interface: ens18

frr_interfaces:
  - { name: ens18, description: infra, address: 10.10.50.11/24 }
  - { name: ens19, description: to-r1-dc1, address: 172.16.255.6/30 }
  - { name: ens20, description: to-r2-dc1, address: 172.16.255.14/30 }
  - { name: ens21, description: server-uplink-a }

leaf_bgp_neighbors:
  - { ip: 172.16.255.5, asn: 65001, desc: r1-dc1 }
  - { ip: 172.16.255.13, asn: 65001, desc: r2-dc1 }

leaf_vlan_interfaces:
  - { vlan: 10, ifname: ens21.10, address: 10.10.10.1/24 }
  - { vlan: 20, ifname: ens21.20, address: 10.10.20.1/24 }
  - { vlan: 50, ifname: ens21.50, address: 10.10.40.1/24 }
  - { vlan: 60, ifname: ens21.60, address: 10.10.60.1/24 }
