---
node_role: leaf
dc: dc1
leaf_asn: 65110
router_id: 10.255.1.11
loopback_ip: 10.255.1.11/32
mylab_primary_ip: 10.10.10.21
mylab_primary_interface: ens18
frr_interfaces:
  - { name: ens18, description: mgmt, address: 10.10.10.21/24 }
  - { name: ens19, description: to-r1-dc1, address: 172.16.255.6/30 }
  - { name: ens20, description: to-r2-dc1, address: 172.16.255.14/30 }
  - { name: ens21, description: server-uplink-a }
leaf_bgp_neighbors:
  - { ip: 172.16.255.5, asn: 65001, desc: r1-dc1 }
  - { ip: 172.16.255.13, asn: 65001, desc: r2-dc1 }
leaf_vlan_interfaces:
  - { vlan: 10, ifname: ens21.10, address: 10.10.10.1/24 }
  - { vlan: 20, ifname: ens21.20, address: 10.10.20.1/24 }
  - { vlan: 30, ifname: ens21.30, address: 10.10.30.1/24 }
