mgmt_interface: ens18
mgmt_ip_cidr: 10.20.0.32/24
mgmt_gateway: 10.20.0.1
leaf_bridges:
  - name: br-fabric
    ports: [ens19, ens20, ens21]
leaf_vlans:
  - id: 210
    name: prod2-node
leaf_svis:
  - name: br-fabric.210
    raw_device: br-fabric
    address: 10.210.0.3/24
