---
node_role: leaf
dc: dc2
leaf_asn: 65120
router_id: 10.255.2.12
loopback_ip: 10.255.2.12/32
mylab_primary_ip: 10.20.10.22
mylab_primary_interface: ens18
frr_interfaces:
  - { name: ens18, description: mgmt, address: 10.20.10.22/24 }
  - { name: ens19, description: to-r1-dc2, address: 172.16.255.42/30 }
  - { name: ens20, description: to-r2-dc2, address: 172.16.255.50/30 }
  - { name: ens21, description: server-uplink-b }
leaf_bgp_neighbors:
  - { ip: 172.16.255.41, asn: 65002, desc: r1-dc2 }
  - { ip: 172.16.255.49, asn: 65002, desc: r2-dc2 }
leaf_vlan_interfaces:
  - { vlan: 10, ifname: ens21.10, address: 10.20.10.2/24 }
  - { vlan: 20, ifname: ens21.20, address: 10.20.20.2/24 }
  - { vlan: 31, ifname: ens21.31, address: 10.20.31.2/24 }
