---
node_role: kube_control_plane
cluster_name: prod2
dc: dc2

mylab_primary_ip: 10.20.20.11
mylab_primary_interface: ens18

network_interfaces:
  - name: ens18
    address: 10.20.20.11/24
    gateway: 10.20.20.1
    dns: "{{ mylab_dns_servers }}"
