---
- name: Configure sysctl baseline
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-mylab.conf
    mode: '0644'
    content: |
      {% for key, value in mylab_sysctl_common.items() %}
      {{ key }} = {{ value }}
      {% endfor %}
  notify: Reload sysctl
