---
- name: Configure systemd-timesyncd
  ansible.builtin.copy:
    dest: "{{ timesync_config_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      [Time]
      NTP={{ mylab_ntp_servers | join(' ') }}
      FallbackNTP={{ timesync_fallback_ntp }}
  notify: Restart timesyncd

- name: Ensure systemd-timesyncd is enabled and started
  ansible.builtin.service:
    name: "{{ timesync_service_name }}"
    state: started
    enabled: true