- name: Configure chrony
  ansible.builtin.copy:
    dest: "{{ timesync_config_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for server in mylab_ntp_servers %}
      pool {{ server }} iburst
      {% endfor %}
  notify: Restart chrony

- name: Ensure chrony is enabled and started
  ansible.builtin.service:
    name: "{{ timesync_service_name }}"
    state: started
    enabled: true