---
hosts:
  bastion1.dc1.lab:
    role: bastion
    dc: dc1
    ip: 10.10.10.10
    vlan: management

  r1-dc1.lab:
    role: router
    dc: dc1
    ip: 10.10.50.1
    vlan: infra
    loopback: 10.255.0.1

  r2-dc1.lab:
    role: router
    dc: dc1
    ip: 10.10.50.2
    vlan: infra
    loopback: 10.255.0.2

  leaf1-dc1.lab:
    role: leaf
    dc: dc1
    ip: 10.10.50.11
    vlan: infra
    loopback: 10.255.0.11

  leaf2-dc1.lab:
    role: leaf
    dc: dc1
    ip: 10.10.50.12
    vlan: infra
    loopback: 10.255.0.12

  r1-dc2.lab:
    role: router
    dc: dc2
    ip: 10.20.50.1
    vlan: infra
    loopback: 10.255.0.21

  r2-dc2.lab:
    role: router
    dc: dc2
    ip: 10.20.50.2
    vlan: infra
    loopback: 10.255.0.22

  leaf1-dc2.lab:
    role: leaf
    dc: dc2
    ip: 10.20.50.11
    vlan: infra
    loopback: 10.255.0.31

  leaf2-dc2.lab:
    role: leaf
    dc: dc2
    ip: 10.20.50.12
    vlan: infra
    loopback: 10.255.0.32

  prod1-cp1.dc1.lab:
    role: k8s-control-plane
    cluster: prod1
    dc: dc1
    ip: 10.10.20.11
    vlan: prod1

  prod1-w1.dc1.lab:
    role: k8s-worker
    cluster: prod1
    dc: dc1
    ip: 10.10.20.21
    vlan: prod1

  prod1-w2.dc1.lab:
    role: k8s-worker
    cluster: prod1
    dc: dc1
    ip: 10.10.20.22
    vlan: prod1

  prod2-cp1.dc2.lab:
    role: k8s-control-plane
    cluster: prod2
    dc: dc2
    ip: 10.20.20.11
    vlan: prod2

  prod2-w1.dc2.lab:
    role: k8s-worker
    cluster: prod2
    dc: dc2
    ip: 10.20.20.21
    vlan: prod2

  prod2-w2.dc2.lab:
    role: k8s-worker
    cluster: prod2
    dc: dc2
    ip: 10.20.20.22
    vlan: prod2
