---
- name: Full infra baseline
  hosts: all
  become: true
  roles:
    - common_base
    - apt_baseline
    - users_admin
    - ssh_hardening
    - time_sync
    - journald
    - sysctl_tuning
    - nftables_base
    - node_exporter

- name: Bastion baseline
  hosts: bastion
  become: true
  roles:
    - bastion_base

- name: Router configuration
  hosts: routers
  become: true
  roles:
    - router_frr

- name: Leaf configuration
  hosts: leafs
  become: true
  roles:
    - leaf_l3

- name: Kubernetes prerequisites
  hosts: k8s_cluster
  become: true
  roles:
    - containerd
    - kubernetes_common
